// data.js - Local dataset of dishes used by Velora
// Each dish object powers both the browsable catalog and the AI recommendation prompt context.

const DISH_DATA = [
  { id: 1, name: 'Paneer Butter Masala', cuisine: 'North Indian', type: 'veg', meal: 'dinner', price: 220, calories: 420, spice: 1, emoji: '🧀', desc: 'Cottage cheese cubes simmered in a rich, buttery tomato gravy.' },
  { id: 2, name: 'Dal Makhani', cuisine: 'North Indian', type: 'veg', meal: 'dinner', price: 180, calories: 380, spice: 1, emoji: '🍛', desc: 'Slow-cooked black lentils in a creamy, buttery finish.' },
  { id: 3, name: 'Butter Chicken', cuisine: 'North Indian', type: 'non-veg', meal: 'dinner', price: 280, calories: 520, spice: 1, emoji: '🍗', desc: 'Tandoori chicken chunks in a velvety tomato-butter sauce.' },
  { id: 4, name: 'Chole Bhature', cuisine: 'North Indian', type: 'veg', meal: 'lunch', price: 150, calories: 650, spice: 2, emoji: '🫓', desc: 'Spicy chickpea curry served with deep-fried fluffy bread.' },
  { id: 5, name: 'Rajma Chawal', cuisine: 'North Indian', type: 'veg', meal: 'lunch', price: 140, calories: 480, spice: 1, emoji: '🍚', desc: 'Kidney bean curry served over steamed basmati rice.' },
  { id: 6, name: 'Tandoori Chicken', cuisine: 'North Indian', type: 'non-veg', meal: 'dinner', price: 300, calories: 410, spice: 2, emoji: '🍗', desc: 'Char-grilled chicken marinated in yogurt and spices.' },
  { id: 7, name: 'Amritsari Kulcha', cuisine: 'North Indian', type: 'veg', meal: 'lunch', price: 120, calories: 410, spice: 1, emoji: '🫓', desc: 'Stuffed leavened bread cooked in a tandoor, served with chole.' },
  { id: 8, name: 'Palak Paneer', cuisine: 'North Indian', type: 'veg', meal: 'dinner', price: 200, calories: 350, spice: 1, emoji: '🥬', desc: 'Cottage cheese cubes in a smooth spinach gravy.' },
  { id: 9, name: 'Mutton Rogan Josh', cuisine: 'North Indian', type: 'non-veg', meal: 'dinner', price: 350, calories: 600, spice: 2, emoji: '🍖', desc: 'Kashmiri-style aromatic mutton curry cooked in yogurt and spices.' },
  { id: 10, name: 'Aloo Paratha', cuisine: 'North Indian', type: 'veg', meal: 'breakfast', price: 90, calories: 350, spice: 1, emoji: '🫓', desc: 'Whole wheat flatbread stuffed with spiced mashed potatoes.' },
  { id: 11, name: 'Malai Kofta', cuisine: 'North Indian', type: 'veg', meal: 'dinner', price: 230, calories: 470, spice: 1, emoji: '🧀', desc: 'Fried vegetable-cheese dumplings in a creamy cashew gravy.' },
  { id: 12, name: 'Kadai Paneer', cuisine: 'North Indian', type: 'veg', meal: 'dinner', price: 210, calories: 400, spice: 2, emoji: '🧀', desc: 'Paneer and bell peppers tossed in a spicy kadai masala.' },
  { id: 13, name: 'Masala Dosa', cuisine: 'South Indian', type: 'veg', meal: 'breakfast', price: 90, calories: 350, spice: 1, emoji: '🥞', desc: 'Crispy fermented rice crepe filled with spiced potato masala.' },
  { id: 14, name: 'Idli Sambar', cuisine: 'South Indian', type: 'veg', meal: 'breakfast', price: 70, calories: 220, spice: 1, emoji: '⚪', desc: 'Steamed rice cakes served with lentil sambar and chutney.' },
  { id: 15, name: 'Medu Vada', cuisine: 'South Indian', type: 'veg', meal: 'breakfast', price: 80, calories: 280, spice: 1, emoji: '🍩', desc: 'Crispy fried lentil doughnuts served with coconut chutney.' },
  { id: 16, name: 'Hyderabadi Biryani', cuisine: 'South Indian', type: 'non-veg', meal: 'lunch', price: 260, calories: 650, spice: 2, emoji: '🍚', desc: 'Fragrant basmati rice layered with spiced marinated meat.' },
  { id: 17, name: 'Rava Upma', cuisine: 'South Indian', type: 'veg', meal: 'breakfast', price: 70, calories: 250, spice: 1, emoji: '🌾', desc: 'Savory semolina porridge tempered with mustard seeds and curry leaves.' },
  { id: 18, name: 'Chettinad Chicken', cuisine: 'South Indian', type: 'non-veg', meal: 'dinner', price: 290, calories: 480, spice: 3, emoji: '🍗', desc: 'Fiery Tamil Nadu style chicken curry with roasted spices.' },
  { id: 19, name: 'Uttapam', cuisine: 'South Indian', type: 'veg', meal: 'breakfast', price: 100, calories: 300, spice: 1, emoji: '🥞', desc: 'Thick savory rice pancake topped with onions and tomatoes.' },
  { id: 20, name: 'Curd Rice', cuisine: 'South Indian', type: 'veg', meal: 'lunch', price: 90, calories: 280, spice: 0, emoji: '🍚', desc: 'Comforting rice mixed with yogurt, tempered with mustard seeds.' },
  { id: 21, name: 'Fish Moilee', cuisine: 'South Indian', type: 'non-veg', meal: 'dinner', price: 280, calories: 420, spice: 1, emoji: '🐟', desc: 'Kerala-style fish simmered in coconut milk and curry leaves.' },
  { id: 22, name: 'Pesarattu', cuisine: 'South Indian', type: 'veg', meal: 'breakfast', price: 85, calories: 260, spice: 1, emoji: '🥞', desc: 'Green gram dosa served with ginger chutney.' },
  { id: 23, name: 'Veg Hakka Noodles', cuisine: 'Chinese', type: 'veg', meal: 'dinner', price: 150, calories: 420, spice: 1, emoji: '🍜', desc: 'Stir-fried noodles tossed with fresh vegetables and soy sauce.' },
  { id: 24, name: 'Chicken Manchurian', cuisine: 'Chinese', type: 'non-veg', meal: 'dinner', price: 220, calories: 480, spice: 2, emoji: '🍗', desc: 'Deep-fried chicken balls tossed in a tangy Indo-Chinese sauce.' },
  { id: 25, name: 'Veg Spring Rolls', cuisine: 'Chinese', type: 'veg', meal: 'snack', price: 130, calories: 300, spice: 1, emoji: '🥟', desc: 'Crispy rolls stuffed with julienned vegetables.' },
  { id: 26, name: 'Kung Pao Chicken', cuisine: 'Chinese', type: 'non-veg', meal: 'dinner', price: 250, calories: 460, spice: 2, emoji: '🍗', desc: 'Spicy stir-fried chicken with peanuts and dried chilies.' },
  { id: 27, name: 'Schezwan Fried Rice', cuisine: 'Chinese', type: 'veg', meal: 'dinner', price: 170, calories: 440, spice: 3, emoji: '🍚', desc: 'Fiery fried rice tossed in a bold schezwan sauce.' },
  { id: 28, name: 'Chilli Paneer', cuisine: 'Chinese', type: 'veg', meal: 'snack', price: 190, calories: 380, spice: 2, emoji: '🧀', desc: 'Crispy paneer tossed with peppers in a spicy soy-chilli sauce.' },
  { id: 29, name: 'Dim Sum', cuisine: 'Chinese', type: 'non-veg', meal: 'snack', price: 210, calories: 320, spice: 1, emoji: '🥟', desc: 'Steamed dumplings filled with minced meat and vegetables.' },
  { id: 30, name: 'Hot and Sour Soup', cuisine: 'Chinese', type: 'veg', meal: 'snack', price: 110, calories: 180, spice: 2, emoji: '🍲', desc: 'Tangy and spicy soup loaded with vegetables and tofu.' },
  { id: 31, name: 'Sweet Corn Soup', cuisine: 'Chinese', type: 'veg', meal: 'snack', price: 100, calories: 150, spice: 0, emoji: '🍲', desc: 'Mild and creamy soup made with sweet corn and vegetables.' },
  { id: 32, name: 'Honey Chilli Potato', cuisine: 'Chinese', type: 'veg', meal: 'snack', price: 160, calories: 410, spice: 2, emoji: '🍟', desc: 'Crispy fried potato fingers glazed in sweet-spicy sauce.' },
  { id: 33, name: 'Margherita Pizza', cuisine: 'Italian', type: 'veg', meal: 'dinner', price: 280, calories: 650, spice: 0, emoji: '🍕', desc: 'Classic pizza topped with tomato, mozzarella, and fresh basil.' },
  { id: 34, name: 'Spaghetti Aglio e Olio', cuisine: 'Italian', type: 'veg', meal: 'dinner', price: 240, calories: 420, spice: 1, emoji: '🍝', desc: 'Simple pasta tossed with garlic, olive oil, and chili flakes.' },
  { id: 35, name: 'Chicken Alfredo Pasta', cuisine: 'Italian', type: 'non-veg', meal: 'dinner', price: 320, calories: 620, spice: 0, emoji: '🍝', desc: 'Creamy alfredo sauce pasta with grilled chicken strips.' },
  { id: 36, name: 'Bruschetta', cuisine: 'Italian', type: 'veg', meal: 'snack', price: 180, calories: 220, spice: 0, emoji: '🫓', desc: 'Toasted bread topped with fresh tomato, garlic, and basil.' },
  { id: 37, name: 'Lasagna', cuisine: 'Italian', type: 'non-veg', meal: 'dinner', price: 350, calories: 700, spice: 1, emoji: '🍝', desc: 'Layered pasta baked with meat sauce, cheese, and bechamel.' },
  { id: 38, name: 'Risotto ai Funghi', cuisine: 'Italian', type: 'veg', meal: 'dinner', price: 300, calories: 480, spice: 0, emoji: '🍚', desc: 'Creamy Arborio rice cooked slowly with mushrooms and parmesan.' },
  { id: 39, name: 'Caprese Salad', cuisine: 'Italian', type: 'veg', meal: 'lunch', price: 200, calories: 250, spice: 0, emoji: '🥗', desc: 'Fresh mozzarella, tomatoes, and basil drizzled with olive oil.' },
  { id: 40, name: 'Pepperoni Pizza', cuisine: 'Italian', type: 'non-veg', meal: 'dinner', price: 320, calories: 720, spice: 1, emoji: '🍕', desc: 'Wood-fired pizza topped with spicy pepperoni and cheese.' },
  { id: 41, name: 'Tiramisu', cuisine: 'Italian', type: 'veg', meal: 'dessert', price: 220, calories: 420, spice: 0, emoji: '🍰', desc: 'Coffee-soaked ladyfingers layered with mascarpone cream.' },
  { id: 42, name: 'Minestrone Soup', cuisine: 'Italian', type: 'veg', meal: 'snack', price: 170, calories: 210, spice: 0, emoji: '🍲', desc: 'Hearty vegetable soup with beans and pasta in tomato broth.' },
  { id: 43, name: 'Chicken Tacos', cuisine: 'Mexican', type: 'non-veg', meal: 'dinner', price: 220, calories: 380, spice: 2, emoji: '🌮', desc: 'Soft tortillas filled with spiced grilled chicken and salsa.' },
  { id: 44, name: 'Veg Burrito Bowl', cuisine: 'Mexican', type: 'veg', meal: 'lunch', price: 210, calories: 450, spice: 1, emoji: '🌯', desc: 'Rice bowl loaded with beans, corn, veggies, and guacamole.' },
  { id: 45, name: 'Nachos Supreme', cuisine: 'Mexican', type: 'veg', meal: 'snack', price: 190, calories: 520, spice: 1, emoji: '🧀', desc: 'Crispy tortilla chips loaded with cheese, jalapenos, and salsa.' },
  { id: 46, name: 'Quesadilla', cuisine: 'Mexican', type: 'veg', meal: 'snack', price: 180, calories: 410, spice: 1, emoji: '🫓', desc: 'Grilled tortilla stuffed with melted cheese and vegetables.' },
  { id: 47, name: 'Beef Burrito', cuisine: 'Mexican', type: 'non-veg', meal: 'dinner', price: 260, calories: 580, spice: 2, emoji: '🌯', desc: 'Tortilla wrap filled with seasoned beef, rice, and beans.' },
  { id: 48, name: 'Guacamole with Chips', cuisine: 'Mexican', type: 'veg', meal: 'snack', price: 160, calories: 320, spice: 0, emoji: '🥑', desc: 'Fresh mashed avocado dip served with crispy tortilla chips.' },
  { id: 49, name: 'Enchiladas', cuisine: 'Mexican', type: 'non-veg', meal: 'dinner', price: 250, calories: 510, spice: 2, emoji: '🌯', desc: 'Rolled tortillas filled with chicken, topped with chili sauce.' },
  { id: 50, name: 'Mexican Rice', cuisine: 'Mexican', type: 'veg', meal: 'lunch', price: 130, calories: 380, spice: 1, emoji: '🍚', desc: 'Tomato-flavored rice cooked with peppers and spices.' },
  { id: 51, name: 'Churros', cuisine: 'Mexican', type: 'veg', meal: 'dessert', price: 150, calories: 350, spice: 0, emoji: '🍰', desc: 'Fried dough pastry dusted with cinnamon sugar, served with chocolate.' },
  { id: 52, name: 'California Roll', cuisine: 'Japanese', type: 'non-veg', meal: 'dinner', price: 280, calories: 320, spice: 0, emoji: '🍣', desc: 'Sushi roll with crab, avocado, and cucumber wrapped in nori.' },
  { id: 53, name: 'Vegetable Tempura', cuisine: 'Japanese', type: 'veg', meal: 'snack', price: 220, calories: 350, spice: 0, emoji: '🍤', desc: 'Lightly battered and fried assorted vegetables.' },
  { id: 54, name: 'Chicken Teriyaki', cuisine: 'Japanese', type: 'non-veg', meal: 'dinner', price: 290, calories: 450, spice: 0, emoji: '🍗', desc: 'Grilled chicken glazed in a sweet-savory teriyaki sauce.' },
  { id: 55, name: 'Miso Soup', cuisine: 'Japanese', type: 'veg', meal: 'snack', price: 120, calories: 90, spice: 0, emoji: '🍲', desc: 'Traditional soup made with fermented soybean paste and tofu.' },
  { id: 56, name: 'Salmon Nigiri', cuisine: 'Japanese', type: 'non-veg', meal: 'dinner', price: 320, calories: 280, spice: 0, emoji: '🍣', desc: 'Hand-pressed sushi rice topped with fresh salmon slices.' },
  { id: 57, name: 'Vegetable Ramen', cuisine: 'Japanese', type: 'veg', meal: 'dinner', price: 240, calories: 480, spice: 1, emoji: '🍜', desc: 'Noodle soup in a savory broth with fresh vegetables.' },
  { id: 58, name: 'Chicken Katsu', cuisine: 'Japanese', type: 'non-veg', meal: 'dinner', price: 270, calories: 520, spice: 0, emoji: '🍗', desc: 'Crispy panko-breaded chicken cutlet served with tonkatsu sauce.' },
  { id: 59, name: 'Edamame', cuisine: 'Japanese', type: 'veg', meal: 'snack', price: 110, calories: 150, spice: 0, emoji: '🫛', desc: 'Steamed young soybeans lightly salted.' },
  { id: 60, name: 'Mochi Ice Cream', cuisine: 'Japanese', type: 'veg', meal: 'dessert', price: 180, calories: 220, spice: 0, emoji: '🍰', desc: 'Soft rice cake filled with a sweet ice cream center.' },
  { id: 61, name: 'Gulab Jamun', cuisine: 'Desserts', type: 'veg', meal: 'dessert', price: 90, calories: 300, spice: 0, emoji: '🍰', desc: 'Soft milk-solid balls soaked in warm rose-flavored sugar syrup.' },
  { id: 62, name: 'Chocolate Brownie', cuisine: 'Desserts', type: 'veg', meal: 'dessert', price: 140, calories: 420, spice: 0, emoji: '🍰', desc: 'Rich, fudgy baked chocolate square served warm.' },
  { id: 63, name: 'Rasmalai', cuisine: 'Desserts', type: 'veg', meal: 'dessert', price: 120, calories: 280, spice: 0, emoji: '🍰', desc: 'Soft cottage cheese dumplings soaked in sweetened saffron milk.' },
  { id: 64, name: 'Ice Cream Sundae', cuisine: 'Desserts', type: 'veg', meal: 'dessert', price: 160, calories: 380, spice: 0, emoji: '🍰', desc: 'Layered ice cream with chocolate sauce, nuts, and a cherry.' },
  { id: 65, name: 'Kheer', cuisine: 'Desserts', type: 'veg', meal: 'dessert', price: 100, calories: 260, spice: 0, emoji: '🍰', desc: 'Traditional rice pudding simmered in sweetened milk with cardamom.' },
  { id: 66, name: 'Cheesecake', cuisine: 'Desserts', type: 'veg', meal: 'dessert', price: 200, calories: 450, spice: 0, emoji: '🍰', desc: 'Creamy baked cheesecake with a buttery biscuit base.' },
  { id: 67, name: 'Jalebi', cuisine: 'Desserts', type: 'veg', meal: 'dessert', price: 80, calories: 320, spice: 0, emoji: '🍰', desc: 'Crispy spiral-shaped batter soaked in sugar syrup.' },
  { id: 68, name: 'Red Velvet Cake', cuisine: 'Desserts', type: 'veg', meal: 'dessert', price: 180, calories: 410, spice: 0, emoji: '🍰', desc: 'Soft cocoa sponge cake layered with cream cheese frosting.' },
  { id: 69, name: 'Masala Chai', cuisine: 'Beverages', type: 'veg', meal: 'beverage', price: 40, calories: 90, spice: 1, emoji: '☕', desc: 'Spiced Indian tea brewed with milk, ginger, and cardamom.' },
  { id: 70, name: 'Cold Coffee', cuisine: 'Beverages', type: 'veg', meal: 'beverage', price: 90, calories: 220, spice: 0, emoji: '☕', desc: 'Chilled blended coffee topped with ice cream.' },
  { id: 71, name: 'Mango Lassi', cuisine: 'Beverages', type: 'veg', meal: 'beverage', price: 80, calories: 250, spice: 0, emoji: '🥭', desc: 'Thick yogurt-based drink blended with sweet mango pulp.' },
  { id: 72, name: 'Fresh Lime Soda', cuisine: 'Beverages', type: 'veg', meal: 'beverage', price: 60, calories: 60, spice: 0, emoji: '🍋', desc: 'Refreshing soda with fresh lime juice, sweet or salted.' },
  { id: 73, name: 'Virgin Mojito', cuisine: 'Beverages', type: 'veg', meal: 'beverage', price: 130, calories: 110, spice: 0, emoji: '🍹', desc: 'Refreshing mocktail with mint, lime, and soda.' },
  { id: 74, name: 'Cappuccino', cuisine: 'Beverages', type: 'veg', meal: 'beverage', price: 110, calories: 120, spice: 0, emoji: '☕', desc: 'Espresso topped with steamed and frothed milk.' },
  { id: 75, name: 'Watermelon Juice', cuisine: 'Beverages', type: 'veg', meal: 'beverage', price: 70, calories: 90, spice: 0, emoji: '🍉', desc: 'Freshly extracted juice from ripe watermelon.' },
  { id: 76, name: 'Iced Green Tea', cuisine: 'Beverages', type: 'veg', meal: 'beverage', price: 90, calories: 40, spice: 0, emoji: '☕', desc: 'Chilled antioxidant-rich green tea served over ice.' },
];

// Cuisine list used for filter buttons and dropdowns
const CUISINE_LIST = ["Beverages", "Chinese", "Desserts", "Italian", "Japanese", "Mexican", "North Indian", "South Indian"];

// Export for use in other scripts (script.js, ai.js)
if (typeof module !== 'undefined') { module.exports = { DISH_DATA, CUISINE_LIST }; }
